export {default as PartnerInbox} from './PartnerInbox'
export {default as PartnerOverview} from './PartnerOverview'
export {default as PaymentHistory} from './PaymentHistory'
export {default as PartnerPrograms} from './PartnerPrograms'
export {default as PartnerReports} from './PartnerReports'
export {default as PartnerPayout} from './PartnerPayout'