export {default as Programs} from "./Programs"
export {default as LeaderBoard} from "./LeaderBoard"
export {default as Profile} from "./Profile"
export {default as SubmitReport} from "./SubmitReport"
export {default as ResearchRegister} from "../Auth/AccountRegister"
export {default as Reward} from "./Reward"